$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)
require 'railman-deployment/version'

Gem::Specification.new do |spec|
  spec.name          = "railman-deployment"
  spec.version       = RailmanDeployment::VERSION
  spec.authors       = ["Igor Jancev"]
  spec.email         = ["igor@masterybits.com"]
  spec.summary       = %q{Capistrano tasks for railman-generated rails applications}
  spec.description   = %q{railman-deployment gem adds capistrano tasks for automated deployment of rails applications generated by railman}
  spec.homepage      = "https://github.com/igorj/railman-deployment"
  spec.license       = "MIT"


  spec.files         = `git ls-files -z`.split("\x0").reject { |f| f.match(%r{^test/}) }
  spec.require_paths = ["lib"]

  spec.add_development_dependency "bundler", "~> 1.11"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "minitest", "~> 5.8"
  spec.add_development_dependency "minitest-reporters", "~> 1.1"
  spec.add_development_dependency "gem-release", "~> 0.7"
  spec.add_development_dependency "geminabox", "~> 0.13"
  spec.add_development_dependency "coveralls"

  spec.add_dependency "capistrano", "~> 3.4"
end
